name: Update Job Application Status

on:
  repository_dispatch:
    types: [mark_job_applied]

jobs:
  update-status:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      
      - name: Set up Python Environment 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update Database Row
        working-directory: ./autonomous_job_finder
        run: |
          python -c "
          from src.utils.db_manager import JobDB
          db = JobDB('data/jobs.db','data/csv')
          
          target_id = ${{ github.event.client_payload.job_id }}
          
          conn = db.connect()
          cursor = conn.cursor
          cursor.execute('UPDATE jobs SET is_applied = 1 WHERE id = ?', (target_id,))
          conn.commit()
          conn.close()
          db._export_to_csv()
          print(f'Successfully marked job {target_id} as applied.)
          "

      - name: Commit and Push Status Change
        working-directory: ./autonomous_job_finder
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add data/jobs.db data/jobs.csv
          git commit -m "chore: mark job ${{ github.event.client_payload.job_id }} as applied [skip ci]"
          git push origin HEAD:master
