name: Update Job Application Status

on:
  repository_dispatch:
    types: [mark_job_applied]

jobs:
  update-status:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      
      - name: Set up Python Environment 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update Database Row
        working-directory: ./autonomous_job_finder
        run: |
          python -c "
          from src.utils.db_manager import JobDB
          db = JobDB('data/jobs.db','data/jobs.csv')
          target_id = ${{ github.event.client_payload.job_id }}
          row_count = db.update_score_and_interest(job_id=target_id, is_applied=1)
          print(f'Successfully updated {row_count} row(s). Job {target_id} is marked as appliesd.')
          "

      - name: Commit and Push Status Change
        working-directory: ./autonomous_job_finder
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add data/jobs.db data/jobs.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update job application state via tracker" && git push)